[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://classroom-portal-backend.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200